### ISSUE TITLE
Could the script support GoLand2017.3?

### ISSUE THREAD

**Issue by zhaoqin192** [caleb/gruvbox-idea#16]
Excuse me, my IDE is GoLand2017.3, and the theme doesn't appear after running the script. But I find the script including goland. Why?

**Comment by zhaoqin192** [comment]
Sorry, the Gruvbox theme has been successfully appeared after I modified the script. Thx

**Comment by caleb** [comment]
Hi,

Are you on macOS or Linux? I can test for myself here.
