### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by idoo** [caleb/gruvbox-idea#5]
Hello, thank you for this port!

What about light color scheme?

**Comment by caleb** [comment]
I would love to create a light gruvbox theme. It’s been something I’ve been thinking about for a little while. I just need to find the time :)

**Comment by zhranklin** [comment]
Nice work! Is there possibility to have a light background version?

**Comment by caleb** [comment]
I would love one. I just haven't gotten around to making it yet.

I wonder if a find and replace of the hex codes would suffice as a starting point...

**Comment by zhranklin** [comment]
@caleb You mean like a perl script?

**Comment by caleb** [comment]
Yeah, that could work...

I have never used the light Gruvbox theme, but I think it would be a good place to start. I don't have time for the next couple weeks to look into this, but this is definitely something I would be interested in having in the project.

**Comment by caleb** [comment]
We now have a light theme!
