### ISSUE TITLE
Unreadable variables in PHPStorm

### ISSUE THREAD

**Issue by ghost** [caleb/gruvbox-idea#8]
Hi,

The colorscheme is not usable with PHPStorm :

![capture d ecran 2016-07-05 a 08 24 30](https://cloud.githubusercontent.com/assets/295478/16575627/0f887cdc-428a-11e6-9571-147b9094b1ea.png)

As you can see, variables are in a red/wine color and it is nearly unreadable.

**Comment by caleb** [comment]
Thanks! I'll take a look at it.

**Comment by caleb** [comment]
Try the newest version and let me know how it looks.

**Comment by ghost** [comment]
![capture d ecran 2016-07-07 a 08 26 58](https://cloud.githubusercontent.com/assets/295478/16644362/a352a2d8-441c-11e6-9ea2-6985d4aed54e.png)

It looks great, thank you very much :)
